---
- become: true
  gather_facts: true
- name: Converge
  hosts: all
  name: Converge
  roles:
    - role: buluma.dhcpd
  vars:
    dhcpd_subnets:
      - netmask: 255.255.255.0
        network: "{{ ansible_facts['default_ipv4'].network }}"
